name = "carrot-market-chat-worker"
main = "src/index.ts"
compatibility_date = "2025-04-01"

[durable_objects]
bindings = [
  { name = "CHAT_ROOM", class_name = "ChatRoom" }
]

[[migrations]]
tag = "v1"
new_classes = ["ChatRoom"]

[vars]
FASTAPI_URL = "http://localhost:8000"
